# Generated by Django 3.2.17 on 2023-03-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0023_auto_20230224_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(db_index=True, help_text='Case名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='testdomain',
            name='name',
            field=models.CharField(db_index=True, help_text='name', max_length=64),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_framework',
            field=models.CharField(choices=[('aktf', 'aktf'), ('tone', 'tone')], db_index=True, default='tone', max_length=64),
        )
    ]
