# Generated by Django 3.2.5 on 2023-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0023_auto_20230224_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineDownloadRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('baseline_id', models.IntegerField(db_index=True, help_text='baseline id')),
                ('state', models.CharField(choices=[('running', '文件打包中'), ('success', '成功'), ('fail', '失败')], default='running', help_text='state', max_length=64)),
                ('target_url', models.CharField(help_text='baseline下载链接', max_length=256, null=True)),
            ],
            options={
                'db_table': 'baseline_download_record',
            },
        ),
        migrations.AlterField(
            model_name='baseconfig',
            name='ws_id',
            field=models.CharField(blank=True, help_text='ws id', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(db_index=True, help_text='Case名称', max_length=255),
        ),
        migrations.AlterField(
            model_name='testdomain',
            name='name',
            field=models.CharField(db_index=True, help_text='name', max_length=64),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='test_framework',
            field=models.CharField(choices=[('aktf', 'aktf'), ('tone', 'tone')], db_index=True, default='tone', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]