# Generated by Django 3.2.5 on 2023-08-23 10:15

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0025_auto_20230413_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetail',
            name='template_detail',
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
    ]
