# Generated by Django 3.2.5 on 2023-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0026_auto_20230803_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfbaselinedetail',
            name='description',
            field=models.TextField(blank=True, help_text='问题描述', null=True),
        ),
        migrations.AddField(
            model_name='reportitemsubcase',
            name='baseline_desc',
            field=models.TextField(blank=True, help_text='基线问题描述', null=True),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='server_info_config',
            field=models.TextField(blank=True, help_text='机器信息显示配置', null=True),
        ),
    ]
