# Generated by Django 3.2.5 on 2024-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tone', '0027_auto_20231114_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('reason', models.CharField(help_text='原因', max_length=1024)),
                ('answer', models.TextField(help_text='答案')),
                ('right_number', models.IntegerField(default=0, help_text='满意次数')),
                ('wrong_number', models.IntegerField(default=0, help_text='不满意次数')),
                ('problem_type', models.CharField(db_index=True, default='其它', help_text='问题类型', max_length=64)),
                ('problem_attribution', models.CharField(db_index=True, default='Other', help_text='问题归属', max_length=64)),
                ('enable', models.BooleanField(db_index=True, default=True, help_text='启用状态')),
            ],
            options={
                'db_table': 'chats_answer',
            },
        ),
        migrations.CreateModel(
            name='ChatsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('contents', models.CharField(help_text='问题描述', max_length=1024)),
                ('status', models.CharField(choices=[('Init', 'Init'), ('Ignore', 'Ignore'), ('Accept', 'Accept')], db_index=True, default='Init', help_text='状态', max_length=64)),
                ('creator', models.IntegerField(help_text='创建者', null=True)),
                ('contents_sources', models.CharField(choices=[('Collect', '问题收集'), ('Suggest', '意见反馈')], db_index=True, default='Collect', help_text='问题来源', max_length=64)),
                ('is_answered', models.BooleanField(db_index=True, default=False, help_text='是否有答案')),
            ],
            options={
                'db_table': 'chats_collection',
            },
        ),
        migrations.CreateModel(
            name='ChatsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('keyword', models.CharField(db_index=True, help_text='问题关键字', max_length=512)),
            ],
            options={
                'db_table': 'chats_keyword',
            },
        ),
        migrations.CreateModel(
            name='ChatsProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('problem', models.CharField(help_text='问题描述', max_length=1024)),
                ('creator', models.IntegerField(help_text='创建者', null=True)),
                ('level', models.IntegerField(db_index=True, default=1, help_text='推荐优先级')),
            ],
            options={
                'db_table': 'chats_problem',
            },
        ),
        migrations.CreateModel(
            name='ChatsProblemAnswerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('problem_id', models.IntegerField(db_index=True, help_text='关联问题ID')),
                ('answer_id', models.IntegerField(db_index=True, help_text='关联答案ID')),
            ],
            options={
                'db_table': 'chats_problem_answer_relation',
            },
        ),
        migrations.CreateModel(
            name='ChatsProblemKeywordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_at')),
                ('gmt_modified', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='modify_at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否被删除')),
                ('problem_id', models.IntegerField(db_index=True, help_text='关联问题ID')),
                ('keyword_id', models.IntegerField(db_index=True, help_text='关联问题关键字ID')),
            ],
            options={
                'db_table': 'chats_problem_keyword_relation',
            },
        ),
    ]
